# Generated by Django 4.2.1 on 2023-05-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField()),
                ('data_atualizacao', models.DateTimeField()),
                ('fuso_horario', models.CharField(default='-03:00', max_length=50)),
                ('linguagem', models.CharField(choices=[('pt', 'Português'), ('es', 'Espanhol'), ('en', 'Inglês')], default='pt', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('deletado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField()),
                ('data_atualizacao', models.DateTimeField()),
                ('data_limite_assinatura', models.DateTimeField()),
                ('assinado', models.BooleanField(default=False)),
                ('company_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_associados_company', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('data_ultima_redefinicao_senha', models.DateTimeField()),
                ('email_verificado', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField()),
                ('data_atualizacao', models.DateTimeField()),
                ('companhia_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_originais', to='core.company')),
                ('companhias_associadas', models.ManyToManyField(related_name='usuarios_associados', to='core.company')),
                ('documentos_associados', models.ManyToManyField(related_name='usuarios_associados', to='core.doc')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='usuario_criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_criados', to='core.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='documentos_associados',
            field=models.ManyToManyField(related_name='companhias_associadas_company', to='core.doc'),
        ),
        migrations.AddField(
            model_name='company',
            name='usuario_criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companhias_criadas', to='core.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='usuarios_convidados',
            field=models.ManyToManyField(related_name='companhias_convidadas', to='core.user'),
        ),
    ]
