# Generated by Django 4.2.1 on 2023-05-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_data_atualizacao_alter_user_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companhia_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_originais', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='companhias_associadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_associados', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='documentos_associados',
            field=models.ManyToManyField(blank=True, related_name='usuarios_associados', to='core.doc'),
        ),
    ]
