# Generated by Django 4.2.1 on 2023-05-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_data_atualizacao_alter_user_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_criacao',
            field=models.DateTimeField(null=True),
        ),
    ]
