# Generated by Django 4.2.1 on 2023-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='data_criacao',
            field=models.DateTimeField(null=True),
        ),
    ]
