# Generated by Django 4.2.1 on 2023-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_doc_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
