# Generated by Django 4.2.1 on 2023-05-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_doc_company_associada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='usuario_criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companhias_criadas', to='core.user'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='assinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doc',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='data_limite_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
